#!/bin/sh
set -e

case "$1" in
    remove|purge)
	if [ -f /etc/apt/trusted.gpg.d/mozillateam-ubuntu-ppa.gpg ]; then
		rm /etc/apt/trusted.gpg.dmozillateam-ubuntu-ppa.gpg
	fi
 if [ -f /etc/apt/trusted.gpg.d/kelebek333-ubuntu-nvidia-legacy.gpg ]; then
		rm /etc/apt/kelebek333-ubuntu-nvidia-legacy.gpg
	fi
	;;
esac
