#!/bin/sh
#
#    10-help-text - print the help text associated with the distro
#    Copyright (C) 2021 Robert Wiley
#
#    Authors: Robert Wiley <ylee@bodhilinux.com
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

printf "\n"
printf " * Documentation:  https://www.bodhilinux.com/w/wiki\n"
printf " * Live chat:      https://discord.com/invite/pvB7MSf\n"
printf " * Forums:         https://bodhilinux.boards.net\n"
printf " * Facebook:       https://www.facebook.com/bodhilinux\n"
printf " * Twitter:        https://twitter.com/ylee2130\n\n"
