#!/bin/sh
set -e

BASE="/usr/share/bodhi/sankhara"

if [ -f "/usr/share/glib-2.0/schemas/org.gnome.epiphany.gschema.xml" ]; then
  sed -i s/t=epiphany/t=bodhi/ /usr/share/glib-2.0/schemas/org.gnome.epiphany.gschema.xml
  sleep 1
  glib-compile-schemas /usr/share/glib-2.0/schemas
fi

if [ -f "/etc/skel/.bashrc" ]; then
  sed -i s/#force_color_prompt/force_color_prompt/g /etc/skel/.bashrc
fi
