#!/bin/sh
set -e
# Automatically added by dh_installdeb/0.0.1-1
dpkg-maintscript-helper rm_conffile /etc/default/motd-news 0.0.1-1 ~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/0.0.1-1
dpkg-maintscript-helper rm_conffile /etc/update-motd.d/50-motd-news -- "$@"
# End automatically added section

if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi


if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'motd-news.timer' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'motd-news.timer' >/dev/null || true
		deb-systemd-helper unmask 'motd-news.timer' >/dev/null || true
	fi
fi

